"""PACE Bitbucket Platform Adapter.

Uses the Bitbucket Cloud REST API v2 to open PRs, issues, and poll pipeline status.

Required environment variables:
    BITBUCKET_USER          — Bitbucket username (for app password auth)
    BITBUCKET_APP_PASSWORD  — App password (Settings → App passwords → create one
                              with: Repositories:Write, Pull requests:Write,
                              Issues:Write, Pipelines:Read)
    BITBUCKET_WORKSPACE     — Workspace slug (e.g. "my-org")
    BITBUCKET_REPO_SLUG     — Repository slug (e.g. "my-project")

Notes:
    - Issues must be enabled on the repository (Settings → Issue tracker).
    - Bitbucket Pipelines must be enabled for CI polling to work.
    - App passwords are preferred over OAuth for CI/CD use.
    - This adapter targets Bitbucket Cloud; Bitbucket Data Center uses a
      different API — use the Jenkins adapter for self-hosted DC instances.
"""

from __future__ import annotations

import time
import yaml
from pathlib import Path

try:
    import requests
    _REQUESTS_AVAILABLE = True
except ImportError:
    _REQUESTS_AVAILABLE = False

from platforms.base import PlatformAdapter

_API_BASE = "https://api.bitbucket.org/2.0"
_REPO_ROOT = Path(__file__).parent.parent.parent


class BitbucketAdapter(PlatformAdapter):
    def __init__(self, user: str, app_password: str, workspace: str, repo_slug: str) -> None:
        self._auth = (user, app_password) if user and app_password else None
        self._workspace = workspace
        self._repo_slug = repo_slug
        self._available = _REQUESTS_AVAILABLE and bool(workspace) and bool(repo_slug) and self._auth is not None

        if not _REQUESTS_AVAILABLE:
            print("[Bitbucket] 'requests' not installed. Run: pip install requests")
        elif not self._auth:
            print("[Bitbucket] BITBUCKET_USER and BITBUCKET_APP_PASSWORD are required.")
        elif not workspace or not repo_slug:
            print("[Bitbucket] BITBUCKET_WORKSPACE and BITBUCKET_REPO_SLUG are required.")

    def _url(self, path: str) -> str:
        return f"{_API_BASE}/repositories/{self._workspace}/{self._repo_slug}{path}"

    def _get(self, path: str, params: dict | None = None) -> dict:
        resp = requests.get(self._url(path), auth=self._auth, params=params, timeout=15)
        resp.raise_for_status()
        return resp.json()

    def _post(self, path: str, json: dict) -> dict:
        resp = requests.post(self._url(path), auth=self._auth, json=json, timeout=15)
        resp.raise_for_status()
        return resp.json()

    # ------------------------------------------------------------------
    # Review PR
    # ------------------------------------------------------------------

    def open_review_pr(self, day: int, pace_dir: Path) -> str:
        if not self._available:
            print("[Bitbucket] Adapter not configured — skipping PR creation.")
            return ""

        start_day = 1
        for candidate_start in [15, 29]:
            if day >= candidate_start:
                start_day = candidate_start
        period = f"Days {start_day}–{day}"

        ship_count, hold_count, deferred_items = 0, 0, []
        for d in range(start_day, day):
            gate_file = pace_dir / f"day-{d}" / "gate.md"
            if gate_file.exists():
                report = yaml.safe_load(gate_file.read_text())
                if report.get("gate_decision") == "SHIP":
                    ship_count += 1
                else:
                    hold_count += 1
                deferred_items.extend(report.get("deferred", []))

        total = ship_count + hold_count
        ship_rate = f"{(ship_count / total * 100):.0f}%" if total else "N/A"
        deferred_section = (
            "\n".join(f"- {item}" for item in deferred_items)
            if deferred_items
            else "None"
        )

        description = f"""## PACE Review Gate — {period}

### Summary

| Metric | Value |
| --- | --- |
| Stories completed | {ship_count}/{total} |
| SHIP rate | {ship_rate} |
| Escalated HOLDs | {hold_count} |

### Deferred Acceptance Criteria

{deferred_section}

### To Continue

Merge this PR. The PACE loop resumes on the next scheduled run.

---

*Generated by PACE Orchestrator — Day {day}*"""

        branch = f"pace/review-day-{day}"
        try:
            pr = self._post("/pullrequests", {
                "title": f"PACE Review Gate — {period}",
                "description": description,
                "source": {"branch": {"name": branch}},
                "destination": {"branch": {"name": "main"}},
                "close_source_branch": False,
            })
            url = pr.get("links", {}).get("html", {}).get("href", "")
            print(f"[Bitbucket] Review PR opened: {url}")
            return url
        except Exception as e:
            print(f"[Bitbucket] Failed to open PR: {e}")
            return ""

    # ------------------------------------------------------------------
    # Escalation issue
    # ------------------------------------------------------------------

    def open_escalation_issue(self, day: int, day_dir: Path) -> str:
        if not self._available:
            print("[Bitbucket] Adapter not configured — skipping issue creation.")
            return ""

        story_text = (day_dir / "story.md").read_text() if (day_dir / "story.md").exists() else "Not available"
        handoff_text = (day_dir / "handoff.md").read_text() if (day_dir / "handoff.md").exists() else "Not available"
        gate_text = (day_dir / "gate.md").read_text() if (day_dir / "gate.md").exists() else "Not available"
        gate_data = yaml.safe_load(gate_text) if (day_dir / "gate.md").exists() else {}
        hold_reason = gate_data.get("hold_reason", "Unknown — see gate report")

        content = f"""PACE could not resolve this HOLD after 2 retries. Human intervention required.

**Blocker:** {hold_reason}

---

### Story Card

```
{story_text}
```

### FORGE Handoff (last attempt)

```
{handoff_text}
```

### GATE Report (last attempt)

```
{gate_text}
```

---

### To Resume

1. Resolve the blocker described above
2. Close this issue
3. The PACE loop will re-run Day {day} on the next scheduled trigger

*Generated by PACE Orchestrator*"""

        try:
            issue = self._post("/issues", {
                "title": f"PACE Day {day} — Escalated HOLD: {hold_reason[:80]}",
                "content": {"raw": content},
                "kind": "bug",
                "priority": "critical",
            })
            url = issue.get("links", {}).get("html", {}).get("href", "")
            print(f"[Bitbucket] Escalation issue opened: {url}")
            return url
        except Exception as e:
            print(f"[Bitbucket] Failed to open issue: {e}")
            return ""

    # ------------------------------------------------------------------
    # CI polling — Bitbucket Pipelines
    # ------------------------------------------------------------------

    def wait_for_commit_ci(
        self,
        sha: str,
        timeout_minutes: int = 15,
        poll_interval: int = 20,
    ) -> dict:
        if not self._available or not sha:
            return {"conclusion": "no_runs", "url": "", "name": "", "sha": sha or ""}

        deadline = time.time() + timeout_minutes * 60
        print(f"[Bitbucket] Waiting for pipeline on {sha[:8]} (timeout: {timeout_minutes}m)...")

        # Bitbucket pipeline states that are terminal
        TERMINAL_STATES = {"COMPLETED", "STOPPED", "FAILED", "ERROR"}

        while time.time() < deadline:
            try:
                data = self._get(
                    "/pipelines/",
                    params={"target.commit.hash": sha, "sort": "-created_on", "pagelen": 5},
                )
            except Exception as e:
                print(f"[Bitbucket] API error while polling pipeline: {e}")
                time.sleep(poll_interval)
                continue

            pipelines = data.get("values", [])
            if not pipelines:
                print(f"[Bitbucket] No pipeline for {sha[:8]} yet, waiting...")
                time.sleep(poll_interval)
                continue

            # Use the most recently created pipeline
            pipeline = pipelines[0]
            state = pipeline.get("state", {})
            state_name = state.get("name", "")
            result = state.get("result", {}).get("name", "")

            if state_name not in TERMINAL_STATES and state_name != "COMPLETED":
                print(f"[Bitbucket] Pipeline #{pipeline.get('build_number')} state: {state_name}, waiting...")
                time.sleep(poll_interval)
                continue

            conclusion = _map_bitbucket_result(result or state_name)
            build_num = pipeline.get("build_number", "?")
            repo_path = f"{self._workspace}/{self._repo_slug}"
            url = f"https://bitbucket.org/{repo_path}/pipelines/results/{build_num}"
            print(f"[Bitbucket] Pipeline #{build_num} complete — {result or state_name}")
            return {
                "conclusion": conclusion,
                "url": url,
                "name": f"pipeline #{build_num}",
                "sha": sha,
            }

        print(f"[Bitbucket] Pipeline wait timed out after {timeout_minutes}m for {sha[:8]}")
        return {"conclusion": "timeout", "url": "", "name": "", "sha": sha}

    # ------------------------------------------------------------------
    # Summary / reporting
    # ------------------------------------------------------------------

    def post_daily_summary(self, day: int, gate_report: dict) -> None:
        decision = gate_report.get("gate_decision", "UNKNOWN")
        icon = "✅" if decision == "SHIP" else "🔴"
        print(f"[Bitbucket] Day {day} summary: {icon} {decision}")

    def write_job_summary(self, markdown: str) -> None:
        # Bitbucket Pipelines has no native job summary UI.
        # Write to a workspace file; archive as an artifact in bitbucket-pipelines.yml if needed.
        out_file = _REPO_ROOT / "pace-summary.md"
        out_file.write_text(markdown)
        print(f"[Bitbucket] Job summary written to: {out_file}")

    # ------------------------------------------------------------------
    # Advisory findings — Bitbucket Issue per backlisted batch
    # ------------------------------------------------------------------

    def push_advisory_items(self, day: int, items: list[dict], agent: str) -> str:
        if not self._available:
            print(f"[Bitbucket] Adapter not configured — skipping advisory issue for {agent}.")
            return ""
        if not items:
            return ""

        finding_lines = "\n".join(
            f"- [{item['id']}] {item['finding']}"
            for item in items
        )

        content = f"""{agent} raised {len(items)} advisory finding(s) on Day {day} that were not resolved after one retry. These are non-blocking but must be cleared on the next clearance day.

### Findings

{finding_lines}

---

### Resolution

1. Address each finding before the next clearance day
2. On a clearance day, SENTINEL/CONDUIT will verify and close resolved items
3. Unresolved items on a clearance day become blockers (HOLD)

*Generated by PACE Orchestrator — Day {day}*"""

        try:
            issue = self._post("/issues", {
                "title": f"PACE Advisory [{agent}] Day {day} — {len(items)} finding(s)",
                "content": {"raw": content},
                "kind": "enhancement",
                "priority": "major",
            })
            url = issue.get("links", {}).get("html", {}).get("href", "")
            print(f"[Bitbucket] Advisory issue opened: {url}")
            return url
        except Exception as e:
            print(f"[Bitbucket] Failed to open advisory issue: {e}")
            return ""


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _map_bitbucket_result(result: str) -> str:
    mapping = {
        "SUCCESSFUL": "success",
        "FAILED": "failure",
        "ERROR": "failure",
        "STOPPED": "cancelled",
        "COMPLETED": "success",
    }
    return mapping.get(result.upper(), "failure")
