"""PACE Bitbucket Platform Adapters.

BitbucketCIAdapter     — CI/CD and PR integration via Bitbucket Cloud REST API v2.
BitbucketTrackerAdapter — Issue tracking via Bitbucket Issues (if enabled on the repo).

Both adapters share credentials:
    BITBUCKET_API_TOKEN  — repository access token (Bearer auth)
    BITBUCKET_WORKSPACE  — workspace slug (e.g. "myteam")
    BITBUCKET_REPO_SLUG  — repository slug (e.g. "my-service")

Note: Bitbucket Issues are a basic tracker (no sprints/epics). For sprint-level
tracking consider using Jira (platform.tracker: jira) alongside Bitbucket CI.
"""

from __future__ import annotations

import time
import yaml
from pathlib import Path

try:
    import requests as _requests
    _REQUESTS_AVAILABLE = True
except ImportError:
    _REQUESTS_AVAILABLE = False

from platforms.base import CIAdapter, TrackerAdapter

_REPO_ROOT = Path(__file__).parent.parent.parent
_BB_API = "https://api.bitbucket.org/2.0"


class _BitbucketBase:
    """Shared credentials and HTTP helper for Bitbucket adapters."""

    def __init__(self, token: str, workspace: str, repo_slug: str) -> None:
        self._token = token
        self._workspace = workspace
        self._repo_slug = repo_slug
        self._available = _REQUESTS_AVAILABLE and bool(token) and bool(workspace) and bool(repo_slug)
        if not _REQUESTS_AVAILABLE:
            print("[Bitbucket] 'requests' not installed. Run: pip install requests")
        elif not token:
            print("[Bitbucket] BITBUCKET_API_TOKEN not set.")
        elif not workspace:
            print("[Bitbucket] BITBUCKET_WORKSPACE not set.")
        elif not repo_slug:
            print("[Bitbucket] BITBUCKET_REPO_SLUG not set.")

    def _headers(self) -> dict:
        return {
            "Authorization": f"Bearer {self._token}",
            "Content-Type": "application/json",
        }

    def _repo_url(self, path: str = "") -> str:
        base = f"{_BB_API}/repositories/{self._workspace}/{self._repo_slug}"
        return f"{base}/{path.lstrip('/')}" if path else base


class BitbucketCIAdapter(_BitbucketBase, CIAdapter):

    # ------------------------------------------------------------------
    # Review PR
    # ------------------------------------------------------------------

    def open_review_pr(self, day: int, pace_dir: Path) -> str:
        if not self._available:
            print("[Bitbucket] Adapter not configured — skipping PR creation.")
            return ""

        start_day = 1
        for candidate_start in [15, 29]:
            if day >= candidate_start:
                start_day = candidate_start
        period = f"Days {start_day}–{day}"

        ship_count, hold_count, deferred_items = 0, 0, []
        for d in range(start_day, day):
            gate_file = pace_dir / f"day-{d}" / "gate.md"
            if gate_file.exists():
                report = yaml.safe_load(gate_file.read_text())
                if report.get("gate_decision") == "SHIP":
                    ship_count += 1
                else:
                    hold_count += 1
                deferred_items.extend(report.get("deferred", []))

        total = ship_count + hold_count
        ship_rate = f"{(ship_count / total * 100):.0f}%" if total else "N/A"
        deferred_section = (
            "\n".join(f"- {item}" for item in deferred_items)
            if deferred_items
            else "None"
        )

        description = f"""## Summary

| Metric | Value |
| --- | --- |
| Stories completed | {ship_count}/{total} |
| SHIP rate | {ship_rate} |
| Escalated HOLDs | {hold_count} |

## Deferred Acceptance Criteria

{deferred_section}

## To Continue

Merge this PR to proceed to Day {day + 1}, or decline it to pause the cycle.

---

*Generated by PACE Orchestrator — Day {day}*"""

        try:
            # Get default branch
            resp = _requests.get(self._repo_url(), headers=self._headers(), timeout=15)
            resp.raise_for_status()
            main_branch = resp.json().get("mainbranch", {}).get("name", "main")

            resp = _requests.post(
                self._repo_url("pullrequests"),
                headers=self._headers(),
                json={
                    "title": f"[PACE Review Gate] {period}",
                    "description": description,
                    "source": {"branch": {"name": f"pace/review-day-{day}"}},
                    "destination": {"branch": {"name": main_branch}},
                    "close_source_branch": True,
                },
                timeout=15,
            )
            resp.raise_for_status()
            url = resp.json().get("links", {}).get("html", {}).get("href", "")
            print(f"[Bitbucket] Review PR opened: {url}")
            return url
        except Exception as e:
            print(f"[Bitbucket] Failed to open review PR: {e}")
            return ""

    # ------------------------------------------------------------------
    # CI polling — Bitbucket Pipelines
    # ------------------------------------------------------------------

    def wait_for_commit_ci(
        self,
        sha: str,
        timeout_minutes: int = 15,
        poll_interval: int = 20,
    ) -> dict:
        if not self._available or not sha:
            print("[Bitbucket] CI polling unavailable — returning no_runs.")
            return {"conclusion": "no_runs", "url": "", "name": "", "sha": sha or ""}

        deadline = time.time() + timeout_minutes * 60
        print(f"[Bitbucket] Waiting for pipeline on {sha[:8]} (timeout: {timeout_minutes}m)...")

        while time.time() < deadline:
            try:
                resp = _requests.get(
                    self._repo_url(f"pipelines/?target.commit.hash={sha}&sort=-created_on&pagelen=5"),
                    headers=self._headers(),
                    timeout=15,
                )
                resp.raise_for_status()
                pipelines = resp.json().get("values", [])
            except Exception as e:
                print(f"[Bitbucket] API error: {e}")
                time.sleep(poll_interval)
                continue

            if not pipelines:
                print(f"[Bitbucket] No pipelines found yet for {sha[:8]}, waiting...")
                time.sleep(poll_interval)
                continue

            pipeline = pipelines[0]
            state = pipeline.get("state", {})
            stage = state.get("name", "")

            if stage in ("PENDING", "IN_PROGRESS"):
                print(f"[Bitbucket] Pipeline {pipeline.get('build_number', '?')} {stage}, waiting...")
                time.sleep(poll_interval)
                continue

            result = state.get("result", {}).get("name", "")
            conclusion = _map_bitbucket_result(result)
            build_number = pipeline.get("build_number", "?")
            web_url = (
                f"https://bitbucket.org/{self._workspace}/{self._repo_slug}"
                f"/pipelines/results/{build_number}"
            )
            print(f"[Bitbucket] Pipeline #{build_number} complete — {result}")
            return {
                "conclusion": conclusion,
                "url": web_url,
                "name": f"pipeline #{build_number}",
                "sha": sha,
            }

        print(f"[Bitbucket] CI wait timed out after {timeout_minutes}m for {sha[:8]}")
        return {"conclusion": "timeout", "url": "", "name": "", "sha": sha}

    # ------------------------------------------------------------------
    # Summary / reporting
    # ------------------------------------------------------------------

    def post_daily_summary(self, day: int, gate_report: dict) -> None:
        decision = gate_report.get("gate_decision", "UNKNOWN")
        icon = "✅" if decision == "SHIP" else "🔴"
        print(f"[Bitbucket] Day {day} summary: {icon} {decision}")

    def write_job_summary(self, markdown: str) -> None:
        out_file = _REPO_ROOT / "pace-summary.md"
        out_file.write_text(markdown)
        print(f"[Bitbucket] Job summary written to: {out_file}")

    # ------------------------------------------------------------------
    # CI/CD variable management — Bitbucket repository variables
    # ------------------------------------------------------------------

    def set_variable(self, name: str, value: str) -> bool:
        if not self._available:
            return False
        try:
            list_url = (
                f"{_BB_API}/repositories/{self._workspace}/{self._repo_slug}"
                f"/pipelines_config/variables/"
            )
            resp = _requests.get(list_url, headers=self._headers(), timeout=15)
            resp.raise_for_status()
            existing = {v["key"]: v["uuid"] for v in resp.json().get("values", [])}

            if name in existing:
                patch_url = f"{list_url}{existing[name]}"
                resp2 = _requests.put(
                    patch_url,
                    headers=self._headers(),
                    json={"key": name, "value": value, "secured": False},
                    timeout=15,
                )
                resp2.raise_for_status()
                print(f"[Bitbucket] Variable {name} updated.")
            else:
                resp2 = _requests.post(
                    list_url,
                    headers=self._headers(),
                    json={"key": name, "value": value, "secured": False},
                    timeout=15,
                )
                resp2.raise_for_status()
                print(f"[Bitbucket] Variable {name} created.")
            return True
        except Exception as e:
            print(f"[Bitbucket] set_variable error: {e}")
            return False


class BitbucketTrackerAdapter(_BitbucketBase, TrackerAdapter):
    """Bitbucket Issues tracker adapter.

    Note: Bitbucket Issues must be enabled in the repository settings.
    Issues is a basic tracker — no sprints or epics. For sprint tracking,
    use Jira (platform.tracker: jira) alongside Bitbucket CI.
    """

    # ------------------------------------------------------------------
    # Escalation issue
    # ------------------------------------------------------------------

    def open_escalation_issue(self, day: int, day_dir: Path, hold_reason: str = "") -> str:
        if not self._available:
            print("[Bitbucket] Adapter not configured — skipping escalation issue.")
            return ""

        story_text = (day_dir / "story.md").read_text() if (day_dir / "story.md").exists() else "Not available"
        handoff_text = (day_dir / "handoff.md").read_text() if (day_dir / "handoff.md").exists() else "Not available"
        gate_text = (day_dir / "gate.md").read_text() if (day_dir / "gate.md").exists() else "Not available"
        if not hold_reason:
            gate_data = yaml.safe_load(gate_text) if (day_dir / "gate.md").exists() else {}
            hold_reason = (gate_data or {}).get("hold_reason", "")
        if not hold_reason and (day_dir / "sentinel.md").exists():
            hold_reason = (yaml.safe_load((day_dir / "sentinel.md").read_text()) or {}).get("hold_reason", "")
        if not hold_reason and (day_dir / "conduit.md").exists():
            hold_reason = (yaml.safe_load((day_dir / "conduit.md").read_text()) or {}).get("hold_reason", "")
        if not hold_reason:
            hold_reason = "Unknown — see agent reports below"

        content = f"""Escalated HOLD — Day {day}

PACE could not resolve this HOLD after 2 retries. Human intervention required.

Blocker: {hold_reason}

---

Story Card:
{story_text}

FORGE Handoff (last attempt):
{handoff_text}

GATE Report (last attempt):
{gate_text}

---

To Resume:
1. Resolve the blocker described above
2. Close this issue
3. Set PACE_PAUSED repository variable to false
4. The PACE loop will re-run Day {day} on the next scheduled trigger

Note: PACE_PAUSED was automatically set to true when this issue was opened.

Generated by PACE Orchestrator"""

        try:
            resp = _requests.post(
                self._repo_url("issues"),
                headers=self._headers(),
                json={
                    "title": f"[PACE HOLD] Day {day} — {hold_reason[:80]}",
                    "content": {"raw": content},
                    "kind": "bug",
                    "priority": "critical",
                },
                timeout=15,
            )
            resp.raise_for_status()
            url = resp.json().get("links", {}).get("html", {}).get("href", "")
            print(f"[Bitbucket] Escalation issue opened: {url}")
            return url
        except Exception as e:
            print(f"[Bitbucket] Failed to open escalation issue: {e}")
            return ""

    # ------------------------------------------------------------------
    # Advisory findings
    # ------------------------------------------------------------------

    def push_advisory_items(self, day: int, items: list[dict], agent: str) -> str:
        if not self._available:
            print(f"[Bitbucket] Adapter not configured — skipping advisory issue for {agent}.")
            return ""
        if not items:
            return ""

        finding_lines = "\n".join(
            f"- [{item['id']}] {item['finding']}"
            for item in items
        )

        content = f"""PACE Advisory — {agent} Day {day}

{agent} raised {len(items)} advisory finding(s) on Day {day} that were not resolved after one retry.

Findings:
{finding_lines}

---

Resolution:
1. Address each finding before the next clearance day
2. On a clearance day, SENTINEL/CONDUIT will verify and clear resolved items
3. Unresolved items on a clearance day become blockers (HOLD)

Generated by PACE Orchestrator — Day {day}"""

        try:
            resp = _requests.post(
                self._repo_url("issues"),
                headers=self._headers(),
                json={
                    "title": f"[PACE Advisory] {agent} Day {day} — {len(items)} finding(s)",
                    "content": {"raw": content},
                    "kind": "task",
                    "priority": "major",
                },
                timeout=15,
            )
            resp.raise_for_status()
            url = resp.json().get("links", {}).get("html", {}).get("href", "")
            print(f"[Bitbucket] Advisory issue opened: {url}")
            return url
        except Exception as e:
            print(f"[Bitbucket] Failed to open advisory issue: {e}")
            return ""


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _map_bitbucket_result(result: str) -> str:
    """Map Bitbucket pipeline result to a PACE CI conclusion string."""
    mapping = {
        "SUCCESSFUL": "success",
        "FAILED": "failure",
        "ERROR": "failure",
        "STOPPED": "cancelled",
    }
    return mapping.get(result.upper(), "failure")