"""PACE GitHub Platform Adapter.

Uses PyGithub to open PRs, issues, and poll GitHub Actions CI status.

Required environment variables:
    GITHUB_TOKEN        — personal access token or Actions-provided token
    GITHUB_REPOSITORY   — "owner/repo" (e.g. "my-org/my-project")
"""

from __future__ import annotations

import os
import time
import yaml
import requests as _requests
from pathlib import Path

from github import Github, GithubException

from platforms.base import PlatformAdapter


class GitHubAdapter(PlatformAdapter):
    def __init__(self, token: str, repo_name: str) -> None:
        self._gh = Github(token) if token else None
        self._repo = None
        if self._gh and repo_name:
            try:
                self._repo = self._gh.get_repo(repo_name)
            except GithubException as e:
                print(f"[GitHub] Could not load repo '{repo_name}': {e}")

    # ------------------------------------------------------------------
    # Review PR
    # ------------------------------------------------------------------

    def open_review_pr(self, day: int, pace_dir: Path) -> str:
        if not self._repo:
            print("[GitHub] No repo configured — skipping PR creation.")
            return ""

        start_day = 1
        for candidate_start in [15, 29]:
            if day >= candidate_start:
                start_day = candidate_start
        period = f"Days {start_day}–{day}"

        ship_count, hold_count, deferred_items = 0, 0, []
        for d in range(start_day, day):
            gate_file = pace_dir / f"day-{d}" / "gate.md"
            if gate_file.exists():
                report = yaml.safe_load(gate_file.read_text())
                if report.get("gate_decision") == "SHIP":
                    ship_count += 1
                else:
                    hold_count += 1
                deferred_items.extend(report.get("deferred", []))

        total = ship_count + hold_count
        ship_rate = f"{(ship_count / total * 100):.0f}%" if total else "N/A"
        deferred_section = (
            "\n".join(f"- {item}" for item in deferred_items)
            if deferred_items
            else "None"
        )

        body = f"""## PACE Review Gate — {period}

### Summary

| Metric | Value |
| --- | --- |
| Stories completed | {ship_count}/{total} |
| SHIP rate | {ship_rate} |
| Escalated HOLDs | {hold_count} |

### Deferred Acceptance Criteria

{deferred_section}

### To Continue

Approve this PR. The PACE loop resumes on the next scheduled run.

To pause: Request changes and add a comment explaining what needs resolution.

---

*Generated by PACE Orchestrator — Day {day}*"""

        branch = f"pace/review-day-{day}"
        try:
            pr = self._repo.create_pull(
                title=f"PACE Review Gate — {period}",
                body=body,
                head=branch,
                base="main",
                draft=False,
            )
            print(f"[GitHub] Review PR opened: {pr.html_url}")
            return pr.html_url
        except GithubException as e:
            print(f"[GitHub] Failed to open PR: {e}")
            return ""

    # ------------------------------------------------------------------
    # Escalation issue
    # ------------------------------------------------------------------

    def open_escalation_issue(self, day: int, day_dir: Path, hold_reason: str = "") -> str:
        if not self._repo:
            print("[GitHub] No repo configured — skipping issue creation.")
            return ""

        story_file = day_dir / "story.md"
        handoff_file = day_dir / "handoff.md"
        gate_file = day_dir / "gate.md"
        sentinel_file = day_dir / "sentinel.md"
        conduit_file = day_dir / "conduit.md"

        story_text = story_file.read_text() if story_file.exists() else "Not available"
        handoff_text = handoff_file.read_text() if handoff_file.exists() else "Not available"
        gate_text = gate_file.read_text() if gate_file.exists() else "Not available"
        sentinel_text = sentinel_file.read_text() if sentinel_file.exists() else None
        conduit_text = conduit_file.read_text() if conduit_file.exists() else None

        # Cascade: orchestrator-tracked reason → gate.md → sentinel.md → conduit.md → fallback
        if not hold_reason:
            gate_data = yaml.safe_load(gate_text) if gate_file.exists() else {}
            hold_reason = (gate_data or {}).get("hold_reason", "")
        if not hold_reason and sentinel_text:
            sentinel_data = yaml.safe_load(sentinel_text) or {}
            hold_reason = sentinel_data.get("hold_reason", "")
        if not hold_reason and conduit_text:
            conduit_data = yaml.safe_load(conduit_text) or {}
            hold_reason = conduit_data.get("hold_reason", "")
        if not hold_reason:
            hold_reason = "Unknown — see agent reports below"

        extra_sections = ""
        if sentinel_text:
            extra_sections += f"""
### SENTINEL Report (last attempt)

```yaml
{sentinel_text}
```
"""
        if conduit_text:
            extra_sections += f"""
### CONDUIT Report (last attempt)

```yaml
{conduit_text}
```
"""

        body = f"""## Escalated HOLD — Day {day}

PACE could not resolve this HOLD after 2 retries. Human intervention required.

**Blocker:** {hold_reason}

---

### Story Card

```yaml
{story_text}
```

### FORGE Handoff (last attempt)

```yaml
{handoff_text}
```

### GATE Report (last attempt)

```yaml
{gate_text}
```
{extra_sections}---

### To Resume

1. Resolve the blocker described above
2. Close this issue
3. Go to **Settings → Secrets and variables → Actions → Variables** and set `PACE_PAUSED` to `false`
4. The PACE loop will re-run Day {day} on the next scheduled trigger

> **Note:** `PACE_PAUSED` was automatically set to `true` when this issue was opened to prevent the pipeline from retrying indefinitely.

*Generated by PACE Orchestrator*"""

        try:
            issue = self._repo.create_issue(
                title=f"PACE Day {day} — Escalated HOLD: {hold_reason[:80]}",
                body=body,
                labels=["pace-hold", f"day-{day}"],
            )
            print(f"[GitHub] Escalation issue opened: {issue.html_url}")
            return issue.html_url
        except GithubException as e:
            print(f"[GitHub] Failed to open issue: {e}")
            return ""

    # ------------------------------------------------------------------
    # CI polling
    # ------------------------------------------------------------------

    def wait_for_commit_ci(
        self,
        sha: str,
        timeout_minutes: int = 15,
        poll_interval: int = 20,
    ) -> dict:
        if not self._repo or not sha:
            return {"conclusion": "no_runs", "url": "", "name": "", "sha": sha}

        try:
            commit_obj = self._repo.get_commit(sha)
            full_sha = commit_obj.sha
        except GithubException:
            full_sha = sha

        deadline = time.time() + timeout_minutes * 60
        print(f"[GitHub] Waiting for CI on {full_sha[:8]} (timeout: {timeout_minutes}m)...")

        SEVERITY = {
            "failure": 0, "timed_out": 1, "cancelled": 2,
            "success": 3, "skipped": 4, "neutral": 5,
        }

        while time.time() < deadline:
            try:
                runs = list(self._repo.get_workflow_runs(head_sha=full_sha))
            except GithubException as e:
                print(f"[GitHub] API error while polling CI: {e}")
                time.sleep(poll_interval)
                continue

            if not runs:
                print(f"[GitHub] No CI runs for {full_sha[:8]} yet, waiting...")
                time.sleep(poll_interval)
                continue

            pending = [r for r in runs if r.status != "completed"]
            if pending:
                names = ", ".join(r.name for r in pending)
                print(f"[GitHub] CI in progress ({names}), waiting...")
                time.sleep(poll_interval)
                continue

            runs_sorted = sorted(runs, key=lambda r: SEVERITY.get(r.conclusion or "neutral", 99))
            worst = runs_sorted[0]
            print(f"[GitHub] CI complete — {worst.conclusion} ({worst.name})")
            return {
                "conclusion": worst.conclusion,
                "url": worst.html_url,
                "name": worst.name,
                "sha": full_sha,
            }

        print(f"[GitHub] CI wait timed out after {timeout_minutes}m for {full_sha[:8]}")
        return {"conclusion": "timeout", "url": "", "name": "", "sha": full_sha}

    # ------------------------------------------------------------------
    # Summary / reporting
    # ------------------------------------------------------------------

    def post_daily_summary(self, day: int, gate_report: dict) -> None:
        decision = gate_report.get("gate_decision", "UNKNOWN")
        icon = "✅" if decision == "SHIP" else "🔴"
        print(f"[GitHub] Day {day} summary: {icon} {decision}")

    def write_job_summary(self, markdown: str) -> None:
        summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
        if not summary_path:
            return
        with open(summary_path, "w") as f:
            f.write(markdown)

    # ------------------------------------------------------------------
    # Advisory findings — GitHub Issue per backlisted batch
    # ------------------------------------------------------------------

    def push_advisory_items(self, day: int, items: list[dict], agent: str) -> str:
        if not self._repo:
            print(f"[GitHub] No repo configured — skipping advisory issue for {agent}.")
            return ""
        if not items:
            return ""

        finding_lines = "\n".join(
            f"- **[{item['id']}]** {item['finding']}"
            for item in items
        )

        body = f"""## PACE Advisory — {agent} Day {day}

{agent} raised {len(items)} advisory finding(s) on Day {day} that were not resolved after one retry. These are **non-blocking** but must be cleared on the next clearance day.

### Findings

{finding_lines}

---

### Resolution

1. Address each finding before the next clearance day
2. On a clearance day, SENTINEL/CONDUIT will verify and close resolved items
3. Unresolved items on a clearance day become blockers (HOLD)

*Generated by PACE Orchestrator — Day {day}*"""

        try:
            issue = self._repo.create_issue(
                title=f"PACE Advisory [{agent}] Day {day} — {len(items)} finding(s)",
                body=body,
                labels=["pace-advisory", f"pace-{agent.lower()}", f"day-{day}"],
            )
            print(f"[GitHub] Advisory issue opened: {issue.html_url}")
            return issue.html_url
        except GithubException as e:
            print(f"[GitHub] Failed to open advisory issue: {e}")
            return ""

    # ------------------------------------------------------------------
    # CI/CD variable management
    # ------------------------------------------------------------------

    def set_variable(self, name: str, value: str) -> bool:
        """Set a GitHub Actions repository variable via the REST API.

        Uses PATCH to update an existing variable; falls back to POST to create it.
        Returns True on success, False on failure (non-fatal — logs the error).
        """
        if not self._repo:
            print(f"[GitHub] No repo configured — cannot set variable {name}.")
            return False

        token = self._repo._requester._Requester__authorizationHeader.split(" ", 1)[-1]
        repo_full = self._repo.full_name
        headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        url = f"https://api.github.com/repos/{repo_full}/actions/variables/{name}"
        payload = {"name": name, "value": value}

        resp = _requests.patch(url, headers=headers, json=payload, timeout=10)
        if resp.status_code == 204:
            print(f"[GitHub] Variable {name} set to {value!r}.")
            return True
        if resp.status_code == 404:
            create_url = f"https://api.github.com/repos/{repo_full}/actions/variables"
            resp = _requests.post(create_url, headers=headers, json=payload, timeout=10)
            if resp.status_code == 201:
                print(f"[GitHub] Variable {name} created with value {value!r}.")
                return True
        print(f"[GitHub] Failed to set variable {name}: {resp.status_code} {resp.text[:200]}")
        return False
