"""PACE GitHub Platform Adapters.

GitHubCIAdapter     — CI/CD and PR integration via GitHub Actions and REST API.
GitHubTrackerAdapter — Issue tracking via GitHub Issues.

Both adapters share credentials:
    GITHUB_TOKEN      — personal access token or Actions ${{ secrets.GITHUB_TOKEN }}
    GITHUB_REPOSITORY — owner/repo (e.g. "myorg/myrepo")
"""

from __future__ import annotations

import os
import time
import yaml
from pathlib import Path

try:
    import requests as _requests
    _REQUESTS_AVAILABLE = True
except ImportError:
    _REQUESTS_AVAILABLE = False

from platforms.base import CIAdapter, TrackerAdapter

_REPO_ROOT = Path(__file__).parent.parent.parent


class _GitHubBase:
    """Shared credentials and HTTP helper for GitHub adapters."""

    def __init__(self, token: str, repo_name: str) -> None:
        self._token = token
        self._repo = repo_name  # "owner/repo"
        self._available = _REQUESTS_AVAILABLE and bool(token) and bool(repo_name)
        if not _REQUESTS_AVAILABLE:
            print("[GitHub] 'requests' not installed. Run: pip install requests")
        elif not token:
            print("[GitHub] GITHUB_TOKEN not set.")
        elif not repo_name:
            print("[GitHub] GITHUB_REPOSITORY not set.")

    def _headers(self) -> dict:
        return {
            "Authorization": f"Bearer {self._token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    def _api(self, path: str) -> str:
        return f"https://api.github.com/repos/{self._repo}/{path.lstrip('/')}"


class GitHubCIAdapter(_GitHubBase, CIAdapter):

    # ------------------------------------------------------------------
    # Review PR
    # ------------------------------------------------------------------

    def open_review_pr(self, day: int, pace_dir: Path) -> str:
        if not self._available:
            print("[GitHub] Adapter not configured — skipping PR creation.")
            return ""

        start_day = 1
        for candidate_start in [15, 29]:
            if day >= candidate_start:
                start_day = candidate_start
        period = f"Days {start_day}–{day}"

        ship_count, hold_count, deferred_items = 0, 0, []
        for d in range(start_day, day):
            gate_file = pace_dir / f"day-{d}" / "gate.md"
            if gate_file.exists():
                report = yaml.safe_load(gate_file.read_text())
                if report.get("gate_decision") == "SHIP":
                    ship_count += 1
                else:
                    hold_count += 1
                deferred_items.extend(report.get("deferred", []))

        total = ship_count + hold_count
        ship_rate = f"{(ship_count / total * 100):.0f}%" if total else "N/A"
        deferred_section = (
            "\n".join(f"- {item}" for item in deferred_items)
            if deferred_items
            else "None"
        )

        body = f"""## Summary

| Metric | Value |
| --- | --- |
| Stories completed | {ship_count}/{total} |
| SHIP rate | {ship_rate} |
| Escalated HOLDs | {hold_count} |

## Deferred Acceptance Criteria

{deferred_section}

## To Continue

Merge this PR to proceed to Day {day + 1}, or close it to pause the cycle.

---

*Generated by PACE Orchestrator — Day {day}*"""

        try:
            # Determine default branch
            resp = _requests.get(
                f"https://api.github.com/repos/{self._repo}",
                headers=self._headers(),
                timeout=15,
            )
            resp.raise_for_status()
            default_branch = resp.json().get("default_branch", "main")

            resp = _requests.post(
                self._api("pulls"),
                headers=self._headers(),
                json={
                    "title": f"[PACE Review Gate] {period}",
                    "body": body,
                    "head": f"pace/review-day-{day}",
                    "base": default_branch,
                },
                timeout=15,
            )
            resp.raise_for_status()
            url = resp.json().get("html_url", "")
            print(f"[GitHub] Review PR opened: {url}")
            return url
        except Exception as e:
            print(f"[GitHub] Failed to open review PR: {e}")
            return ""

    # ------------------------------------------------------------------
    # CI polling
    # ------------------------------------------------------------------

    def wait_for_commit_ci(
        self,
        sha: str,
        timeout_minutes: int = 15,
        poll_interval: int = 20,
    ) -> dict:
        if not self._available or not sha:
            print("[GitHub] CI polling unavailable — returning no_runs.")
            return {"conclusion": "no_runs", "url": "", "name": "", "sha": sha or ""}

        deadline = time.time() + timeout_minutes * 60
        print(f"[GitHub] Waiting for CI on {sha[:8]} (timeout: {timeout_minutes}m)...")

        while time.time() < deadline:
            try:
                resp = _requests.get(
                    self._api(f"commits/{sha}/check-runs"),
                    headers=self._headers(),
                    timeout=15,
                )
                resp.raise_for_status()
                runs = resp.json().get("check_runs", [])
            except Exception as e:
                print(f"[GitHub] API error: {e}")
                # 422 means the commit is unknown to the check-runs API (e.g. pushed
                # to a branch that never triggered a CI workflow). Retrying won't help.
                if hasattr(e, "response") and getattr(e.response, "status_code", None) == 422:
                    print(f"[GitHub] 422 — no CI workflow associated with {sha[:8]}. Returning no_runs.")
                    return {"conclusion": "no_runs", "url": "", "name": "", "sha": sha}
                time.sleep(poll_interval)
                continue

            if not runs:
                print(f"[GitHub] No check runs found yet for {sha[:8]}, waiting...")
                time.sleep(poll_interval)
                continue

            in_progress = [r for r in runs if r.get("status") != "completed"]
            if in_progress:
                names = ", ".join(r.get("name", "?") for r in in_progress[:3])
                print(f"[GitHub] {len(in_progress)} run(s) still in progress ({names}...), waiting...")
                time.sleep(poll_interval)
                continue

            # All runs completed — check conclusions
            conclusions = [r.get("conclusion", "") for r in runs]
            if any(c in ("failure", "timed_out", "action_required") for c in conclusions):
                conclusion = "failure"
            elif all(c in ("success", "neutral", "skipped") for c in conclusions):
                conclusion = "success"
            elif any(c == "cancelled" for c in conclusions):
                conclusion = "cancelled"
            else:
                conclusion = "failure"

            best = runs[0]
            print(f"[GitHub] CI complete — {conclusion} (checked {len(runs)} run(s))")
            return {
                "conclusion": conclusion,
                "url": best.get("html_url", ""),
                "name": best.get("name", ""),
                "sha": sha,
            }

        print(f"[GitHub] CI wait timed out after {timeout_minutes}m for {sha[:8]}")
        return {"conclusion": "timeout", "url": "", "name": "", "sha": sha}

    # ------------------------------------------------------------------
    # Summary / reporting
    # ------------------------------------------------------------------

    def post_daily_summary(self, day: int, gate_report: dict) -> None:
        decision = gate_report.get("gate_decision", "UNKNOWN")
        icon = "✅" if decision == "SHIP" else "🔴"
        print(f"[GitHub] Day {day} summary: {icon} {decision}")

    def write_job_summary(self, markdown: str) -> None:
        summary_file = os.environ.get("GITHUB_STEP_SUMMARY", "")
        if summary_file:
            try:
                with open(summary_file, "a") as f:
                    f.write(markdown)
                print("[GitHub] Job summary written to GITHUB_STEP_SUMMARY.")
                return
            except OSError as e:
                print(f"[GitHub] Could not write to GITHUB_STEP_SUMMARY: {e}")
        # Fallback
        out_file = _REPO_ROOT / "pace-summary.md"
        out_file.write_text(markdown)
        print(f"[GitHub] Job summary written to: {out_file}")

    # ------------------------------------------------------------------
    # CI/CD variable management (GitHub Actions variables)
    # ------------------------------------------------------------------

    def set_variable(self, name: str, value: str) -> bool:
        if not self._available:
            return False
        try:
            resp = _requests.post(
                self._api(f"actions/variables"),
                headers=self._headers(),
                json={"name": name, "value": value},
                timeout=15,
            )
            if resp.status_code in (201, 204):
                print(f"[GitHub] Variable {name} set.")
                return True
            # Try PATCH if POST returns 409 (already exists)
            resp2 = _requests.patch(
                self._api(f"actions/variables/{name}"),
                headers=self._headers(),
                json={"name": name, "value": value},
                timeout=15,
            )
            if resp2.status_code in (200, 204):
                print(f"[GitHub] Variable {name} updated.")
                return True
            print(f"[GitHub] set_variable failed: {resp2.status_code} {resp2.text[:200]}")
            return False
        except Exception as e:
            print(f"[GitHub] set_variable error: {e}")
            return False


class GitHubTrackerAdapter(_GitHubBase, TrackerAdapter):

    # ------------------------------------------------------------------
    # Escalation issue
    # ------------------------------------------------------------------

    def open_escalation_issue(self, day: int, day_dir: Path, hold_reason: str = "") -> str:
        if not self._available:
            print("[GitHub] Adapter not configured — skipping escalation issue.")
            return ""

        story_text = (day_dir / "story.md").read_text() if (day_dir / "story.md").exists() else "Not available"
        handoff_text = (day_dir / "handoff.md").read_text() if (day_dir / "handoff.md").exists() else "Not available"
        gate_text = (day_dir / "gate.md").read_text() if (day_dir / "gate.md").exists() else "Not available"
        if not hold_reason:
            gate_data = yaml.safe_load(gate_text) if (day_dir / "gate.md").exists() else {}
            hold_reason = (gate_data or {}).get("hold_reason", "")
        if not hold_reason and (day_dir / "sentinel.md").exists():
            hold_reason = (yaml.safe_load((day_dir / "sentinel.md").read_text()) or {}).get("hold_reason", "")
        if not hold_reason and (day_dir / "conduit.md").exists():
            hold_reason = (yaml.safe_load((day_dir / "conduit.md").read_text()) or {}).get("hold_reason", "")
        if not hold_reason:
            hold_reason = "Unknown — see agent reports below"

        body = f"""## Escalated HOLD — Day {day}

PACE could not resolve this HOLD after 2 retries. Human intervention required.

**Blocker:** {hold_reason}

---

### Story Card

```yaml
{story_text}
```

### FORGE Handoff (last attempt)

```yaml
{handoff_text}
```

### GATE Report (last attempt)

```yaml
{gate_text}
```

---

### To Resume

1. Resolve the blocker described above
2. Close this issue
3. Set `PACE_PAUSED` Actions variable to `false`
4. The PACE loop will re-run Day {day} on the next scheduled trigger

> **Note:** `PACE_PAUSED` was automatically set to `true` when this issue was opened.

*Generated by PACE Orchestrator*"""

        try:
            resp = _requests.post(
                self._api("issues"),
                headers=self._headers(),
                json={
                    "title": f"[PACE HOLD] Day {day} — {hold_reason[:80]}",
                    "body": body,
                    "labels": ["pace-hold", f"pace-day-{day}"],
                },
                timeout=15,
            )
            resp.raise_for_status()
            url = resp.json().get("html_url", "")
            print(f"[GitHub] Escalation issue opened: {url}")
            return url
        except Exception as e:
            print(f"[GitHub] Failed to open escalation issue: {e}")
            return ""

    # ------------------------------------------------------------------
    # Advisory findings
    # ------------------------------------------------------------------

    def push_advisory_items(self, day: int, items: list[dict], agent: str) -> str:
        if not self._available:
            print(f"[GitHub] Adapter not configured — skipping advisory issue for {agent}.")
            return ""
        if not items:
            return ""

        finding_lines = "\n".join(
            f"- [{item['id']}] {item['finding']}"
            for item in items
        )

        body = f"""## PACE Advisory — {agent} Day {day}

{agent} raised {len(items)} advisory finding(s) on Day {day} that were not resolved after one retry.

### Findings

{finding_lines}

---

### Resolution

1. Address each finding before the next clearance day
2. On a clearance day, SENTINEL/CONDUIT will verify and clear resolved items
3. Unresolved items on a clearance day become blockers (HOLD)

*Generated by PACE Orchestrator — Day {day}*"""

        try:
            resp = _requests.post(
                self._api("issues"),
                headers=self._headers(),
                json={
                    "title": f"[PACE Advisory] {agent} Day {day} — {len(items)} finding(s)",
                    "body": body,
                    "labels": ["pace-advisory", f"pace-{agent.lower()}", f"pace-day-{day}"],
                },
                timeout=15,
            )
            resp.raise_for_status()
            url = resp.json().get("html_url", "")
            print(f"[GitHub] Advisory issue opened: {url}")
            return url
        except Exception as e:
            print(f"[GitHub] Failed to open advisory issue: {e}")
            return ""