"""PACE GitLab Platform Adapter.

Uses python-gitlab to open MRs, issues, and poll GitLab CI pipeline status.

Required environment variables:
    GITLAB_TOKEN    — personal access token or CI_JOB_TOKEN
    GITLAB_PROJECT  — "group/project" (e.g. "my-org/my-project")

Optional environment variables:
    GITLAB_URL      — GitLab instance URL (default: https://gitlab.com)
"""

from __future__ import annotations

import os
import time
import yaml
from pathlib import Path

try:
    import gitlab
    from gitlab.exceptions import GitlabError
    _GITLAB_AVAILABLE = True
except ImportError:
    _GITLAB_AVAILABLE = False

from platforms.base import PlatformAdapter


class GitLabAdapter(PlatformAdapter):
    def __init__(self, url: str, token: str, project: str) -> None:
        self._project = None
        if not _GITLAB_AVAILABLE:
            print("[GitLab] python-gitlab not installed. Run: pip install python-gitlab")
            return
        if not token or not project:
            print("[GitLab] GITLAB_TOKEN and GITLAB_PROJECT are required.")
            return
        try:
            gl = gitlab.Gitlab(url or "https://gitlab.com", private_token=token)
            gl.auth()
            self._project = gl.projects.get(project)
        except Exception as e:
            print(f"[GitLab] Could not connect to project '{project}': {e}")

    # ------------------------------------------------------------------
    # Review MR
    # ------------------------------------------------------------------

    def open_review_pr(self, day: int, pace_dir: Path) -> str:
        if not self._project:
            print("[GitLab] No project configured — skipping MR creation.")
            return ""

        start_day = 1
        for candidate_start in [15, 29]:
            if day >= candidate_start:
                start_day = candidate_start
        period = f"Days {start_day}–{day}"

        ship_count, hold_count, deferred_items = 0, 0, []
        for d in range(start_day, day):
            gate_file = pace_dir / f"day-{d}" / "gate.md"
            if gate_file.exists():
                report = yaml.safe_load(gate_file.read_text())
                if report.get("gate_decision") == "SHIP":
                    ship_count += 1
                else:
                    hold_count += 1
                deferred_items.extend(report.get("deferred", []))

        total = ship_count + hold_count
        ship_rate = f"{(ship_count / total * 100):.0f}%" if total else "N/A"
        deferred_section = (
            "\n".join(f"- {item}" for item in deferred_items)
            if deferred_items
            else "None"
        )

        description = f"""## PACE Review Gate — {period}

### Summary

| Metric | Value |
| --- | --- |
| Stories completed | {ship_count}/{total} |
| SHIP rate | {ship_rate} |
| Escalated HOLDs | {hold_count} |

### Deferred Acceptance Criteria

{deferred_section}

### To Continue

Merge this MR. The PACE loop resumes on the next scheduled run.

---

*Generated by PACE Orchestrator — Day {day}*"""

        branch = f"pace/review-day-{day}"
        try:
            mr = self._project.mergerequests.create({
                "source_branch": branch,
                "target_branch": "main",
                "title": f"PACE Review Gate — {period}",
                "description": description,
                "labels": ["pace-review"],
            })
            print(f"[GitLab] Review MR opened: {mr.web_url}")
            return mr.web_url
        except Exception as e:
            print(f"[GitLab] Failed to open MR: {e}")
            return ""

    # ------------------------------------------------------------------
    # Escalation issue
    # ------------------------------------------------------------------

    def open_escalation_issue(self, day: int, day_dir: Path) -> str:
        if not self._project:
            print("[GitLab] No project configured — skipping issue creation.")
            return ""

        story_text = (day_dir / "story.md").read_text() if (day_dir / "story.md").exists() else "Not available"
        handoff_text = (day_dir / "handoff.md").read_text() if (day_dir / "handoff.md").exists() else "Not available"
        gate_text = (day_dir / "gate.md").read_text() if (day_dir / "gate.md").exists() else "Not available"
        gate_data = yaml.safe_load(gate_text) if (day_dir / "gate.md").exists() else {}
        hold_reason = gate_data.get("hold_reason", "Unknown — see gate report")

        description = f"""## Escalated HOLD — Day {day}

PACE could not resolve this HOLD after 2 retries. Human intervention required.

**Blocker:** {hold_reason}

---

### Story Card

```yaml
{story_text}
```

### FORGE Handoff (last attempt)

```yaml
{handoff_text}
```

### GATE Report (last attempt)

```yaml
{gate_text}
```

---

### To Resume

1. Resolve the blocker described above
2. Close this issue
3. The PACE loop will re-run Day {day} on the next scheduled trigger

*Generated by PACE Orchestrator*"""

        try:
            issue = self._project.issues.create({
                "title": f"PACE Day {day} — Escalated HOLD: {hold_reason[:80]}",
                "description": description,
                "labels": ["pace-hold"],
            })
            print(f"[GitLab] Escalation issue opened: {issue.web_url}")
            return issue.web_url
        except Exception as e:
            print(f"[GitLab] Failed to open issue: {e}")
            return ""

    # ------------------------------------------------------------------
    # CI polling — GitLab Pipelines
    # ------------------------------------------------------------------

    def wait_for_commit_ci(
        self,
        sha: str,
        timeout_minutes: int = 15,
        poll_interval: int = 20,
    ) -> dict:
        if not self._project or not sha:
            return {"conclusion": "no_runs", "url": "", "name": "", "sha": sha}

        deadline = time.time() + timeout_minutes * 60
        print(f"[GitLab] Waiting for pipeline on {sha[:8]} (timeout: {timeout_minutes}m)...")

        # GitLab terminal statuses
        TERMINAL = {"success", "failed", "canceled", "skipped"}
        # Map GitLab status → PACE conclusion
        STATUS_MAP = {
            "success": "success",
            "failed": "failure",
            "canceled": "cancelled",
            "skipped": "success",  # treat as non-blocking
        }

        while time.time() < deadline:
            try:
                pipelines = self._project.pipelines.list(sha=sha, get_all=False)
            except Exception as e:
                print(f"[GitLab] API error while polling pipeline: {e}")
                time.sleep(poll_interval)
                continue

            if not pipelines:
                print(f"[GitLab] No pipeline for {sha[:8]} yet, waiting...")
                time.sleep(poll_interval)
                continue

            # Use the most recently created pipeline for this SHA
            pipeline = pipelines[0]
            status = pipeline.status

            if status not in TERMINAL:
                print(f"[GitLab] Pipeline {pipeline.id} status: {status}, waiting...")
                time.sleep(poll_interval)
                continue

            conclusion = STATUS_MAP.get(status, "failure")
            url = getattr(pipeline, "web_url", "")
            print(f"[GitLab] Pipeline complete — {status} (pipeline #{pipeline.id})")
            return {
                "conclusion": conclusion,
                "url": url,
                "name": f"pipeline #{pipeline.id}",
                "sha": sha,
            }

        print(f"[GitLab] Pipeline wait timed out after {timeout_minutes}m for {sha[:8]}")
        return {"conclusion": "timeout", "url": "", "name": "", "sha": sha}

    # ------------------------------------------------------------------
    # Summary / reporting
    # ------------------------------------------------------------------

    def post_daily_summary(self, day: int, gate_report: dict) -> None:
        decision = gate_report.get("gate_decision", "UNKNOWN")
        icon = "✅" if decision == "SHIP" else "🔴"
        print(f"[GitLab] Day {day} summary: {icon} {decision}")

    def write_job_summary(self, markdown: str) -> None:
        # GitLab 15.5+ supports $CI_JOB_SUMMARY (append model, same as GitHub)
        summary_path = os.environ.get("CI_JOB_SUMMARY")
        if summary_path:
            with open(summary_path, "a") as f:
                f.write(markdown)
            return
        # Fallback: write to a file in the workspace
        fallback = Path(os.environ.get("CI_PROJECT_DIR", ".")) / "pace-summary.md"
        fallback.write_text(markdown)
        print(f"[GitLab] Job summary written to {fallback}")

    # ------------------------------------------------------------------
    # Advisory findings — GitLab Issue per backlisted batch
    # ------------------------------------------------------------------

    def push_advisory_items(self, day: int, items: list[dict], agent: str) -> str:
        if not self._project:
            print(f"[GitLab] No project configured — skipping advisory issue for {agent}.")
            return ""
        if not items:
            return ""

        finding_lines = "\n".join(
            f"- **[{item['id']}]** {item['finding']}"
            for item in items
        )

        description = f"""## PACE Advisory — {agent} Day {day}

{agent} raised {len(items)} advisory finding(s) on Day {day} that were not resolved after one retry. These are **non-blocking** but must be cleared on the next clearance day.

### Findings

{finding_lines}

---

### Resolution

1. Address each finding before the next clearance day
2. On a clearance day, SENTINEL/CONDUIT will verify and close resolved items
3. Unresolved items on a clearance day become blockers (HOLD)

*Generated by PACE Orchestrator — Day {day}*"""

        try:
            issue = self._project.issues.create({
                "title": f"PACE Advisory [{agent}] Day {day} — {len(items)} finding(s)",
                "description": description,
                "labels": ["pace-advisory", f"pace-{agent.lower()}"],
            })
            print(f"[GitLab] Advisory issue opened: {issue.web_url}")
            return issue.web_url
        except Exception as e:
            print(f"[GitLab] Failed to open advisory issue: {e}")
            return ""
