"""PACE GitLab Platform Adapters.

GitLabCIAdapter     — CI/CD and MR integration via GitLab REST API.
GitLabTrackerAdapter — Issue tracking via GitLab Issues.

Both adapters share credentials:
    GITLAB_TOKEN   — personal access token or CI job token ($CI_JOB_TOKEN)
    GITLAB_PROJECT — project path (e.g. "mygroup/myrepo") or numeric ID
    GITLAB_URL     — optional base URL (default: https://gitlab.com)
"""

from __future__ import annotations

import os
import time
import urllib.parse
import yaml
from pathlib import Path

try:
    import requests as _requests
    _REQUESTS_AVAILABLE = True
except ImportError:
    _REQUESTS_AVAILABLE = False

from platforms.base import CIAdapter, TrackerAdapter

_REPO_ROOT = Path(__file__).parent.parent.parent


class _GitLabBase:
    """Shared credentials and HTTP helper for GitLab adapters."""

    def __init__(self, url: str, token: str, project: str) -> None:
        self._base = url.rstrip("/") if url else "https://gitlab.com"
        self._token = token
        self._project = project  # "group/repo" or numeric ID
        self._available = _REQUESTS_AVAILABLE and bool(token) and bool(project)
        if not _REQUESTS_AVAILABLE:
            print("[GitLab] 'requests' not installed. Run: pip install requests")
        elif not token:
            print("[GitLab] GITLAB_TOKEN not set.")
        elif not project:
            print("[GitLab] GITLAB_PROJECT not set.")

    def _headers(self) -> dict:
        return {"PRIVATE-TOKEN": self._token, "Content-Type": "application/json"}

    def _project_api(self, path: str) -> str:
        encoded = urllib.parse.quote(self._project, safe="")
        return f"{self._base}/api/v4/projects/{encoded}/{path.lstrip('/')}"


class GitLabCIAdapter(_GitLabBase, CIAdapter):

    # ------------------------------------------------------------------
    # Review MR
    # ------------------------------------------------------------------

    def open_review_pr(self, day: int, pace_dir: Path) -> str:
        if not self._available:
            print("[GitLab] Adapter not configured — skipping MR creation.")
            return ""

        start_day = 1
        for candidate_start in [15, 29]:
            if day >= candidate_start:
                start_day = candidate_start
        period = f"Days {start_day}–{day}"

        ship_count, hold_count, deferred_items = 0, 0, []
        for d in range(start_day, day):
            gate_file = pace_dir / f"day-{d}" / "gate.md"
            if gate_file.exists():
                report = yaml.safe_load(gate_file.read_text())
                if report.get("gate_decision") == "SHIP":
                    ship_count += 1
                else:
                    hold_count += 1
                deferred_items.extend(report.get("deferred", []))

        total = ship_count + hold_count
        ship_rate = f"{(ship_count / total * 100):.0f}%" if total else "N/A"
        deferred_section = (
            "\n".join(f"- {item}" for item in deferred_items)
            if deferred_items
            else "None"
        )

        body = f"""## Summary

| Metric | Value |
| --- | --- |
| Stories completed | {ship_count}/{total} |
| SHIP rate | {ship_rate} |
| Escalated HOLDs | {hold_count} |

## Deferred Acceptance Criteria

{deferred_section}

## To Continue

Merge this MR to proceed to Day {day + 1}, or close it to pause the cycle.

---

*Generated by PACE Orchestrator — Day {day}*"""

        try:
            # Get default branch
            resp = _requests.get(
                self._project_api(""),
                headers=self._headers(),
                timeout=15,
            )
            resp.raise_for_status()
            default_branch = resp.json().get("default_branch", "main")

            resp = _requests.post(
                self._project_api("merge_requests"),
                headers=self._headers(),
                json={
                    "title": f"[PACE Review Gate] {period}",
                    "description": body,
                    "source_branch": f"pace/review-day-{day}",
                    "target_branch": default_branch,
                },
                timeout=15,
            )
            resp.raise_for_status()
            url = resp.json().get("web_url", "")
            print(f"[GitLab] Review MR opened: {url}")
            return url
        except Exception as e:
            print(f"[GitLab] Failed to open review MR: {e}")
            return ""

    # ------------------------------------------------------------------
    # CI polling
    # ------------------------------------------------------------------

    def wait_for_commit_ci(
        self,
        sha: str,
        timeout_minutes: int = 15,
        poll_interval: int = 20,
    ) -> dict:
        if not self._available or not sha:
            print("[GitLab] CI polling unavailable — returning no_runs.")
            return {"conclusion": "no_runs", "url": "", "name": "", "sha": sha or ""}

        deadline = time.time() + timeout_minutes * 60
        print(f"[GitLab] Waiting for CI on {sha[:8]} (timeout: {timeout_minutes}m)...")

        while time.time() < deadline:
            try:
                resp = _requests.get(
                    self._project_api(f"commits/{sha}/statuses"),
                    headers=self._headers(),
                    timeout=15,
                )
                resp.raise_for_status()
                statuses = resp.json()
            except Exception as e:
                print(f"[GitLab] API error: {e}")
                time.sleep(poll_interval)
                continue

            if not statuses:
                print(f"[GitLab] No pipeline statuses found yet for {sha[:8]}, waiting...")
                time.sleep(poll_interval)
                continue

            running = [s for s in statuses if s.get("status") in ("pending", "running")]
            if running:
                print(f"[GitLab] {len(running)} pipeline(s) still running, waiting...")
                time.sleep(poll_interval)
                continue

            status_values = [s.get("status", "") for s in statuses]
            if any(s == "failed" for s in status_values):
                conclusion = "failure"
            elif all(s in ("success", "skipped") for s in status_values):
                conclusion = "success"
            elif any(s == "canceled" for s in status_values):
                conclusion = "cancelled"
            else:
                conclusion = "failure"

            best = statuses[0]
            print(f"[GitLab] CI complete — {conclusion}")
            return {
                "conclusion": conclusion,
                "url": best.get("target_url", ""),
                "name": best.get("name", ""),
                "sha": sha,
            }

        print(f"[GitLab] CI wait timed out after {timeout_minutes}m for {sha[:8]}")
        return {"conclusion": "timeout", "url": "", "name": "", "sha": sha}

    # ------------------------------------------------------------------
    # Summary / reporting
    # ------------------------------------------------------------------

    def post_daily_summary(self, day: int, gate_report: dict) -> None:
        decision = gate_report.get("gate_decision", "UNKNOWN")
        icon = "✅" if decision == "SHIP" else "🔴"
        print(f"[GitLab] Day {day} summary: {icon} {decision}")

    def write_job_summary(self, markdown: str) -> None:
        summary_file = os.environ.get("CI_JOB_SUMMARY", "")
        if summary_file:
            try:
                with open(summary_file, "a") as f:
                    f.write(markdown)
                print("[GitLab] Job summary written to CI_JOB_SUMMARY.")
                return
            except OSError as e:
                print(f"[GitLab] Could not write to CI_JOB_SUMMARY: {e}")
        out_file = _REPO_ROOT / "pace-summary.md"
        out_file.write_text(markdown)
        print(f"[GitLab] Job summary written to: {out_file}")

    # ------------------------------------------------------------------
    # CI/CD variable management
    # ------------------------------------------------------------------

    def set_variable(self, name: str, value: str) -> bool:
        if not self._available:
            return False
        try:
            encoded = urllib.parse.quote(self._project, safe="")
            var_url = f"{self._base}/api/v4/projects/{encoded}/variables/{name}"
            resp = _requests.put(
                var_url,
                headers=self._headers(),
                json={"value": value},
                timeout=15,
            )
            if resp.status_code == 200:
                print(f"[GitLab] Variable {name} updated.")
                return True
            # Variable may not exist yet — try POST
            create_url = f"{self._base}/api/v4/projects/{encoded}/variables"
            resp2 = _requests.post(
                create_url,
                headers=self._headers(),
                json={"key": name, "value": value},
                timeout=15,
            )
            if resp2.status_code == 201:
                print(f"[GitLab] Variable {name} created.")
                return True
            print(f"[GitLab] set_variable failed: {resp2.status_code} {resp2.text[:200]}")
            return False
        except Exception as e:
            print(f"[GitLab] set_variable error: {e}")
            return False


class GitLabTrackerAdapter(_GitLabBase, TrackerAdapter):

    # ------------------------------------------------------------------
    # Escalation issue
    # ------------------------------------------------------------------

    def open_escalation_issue(self, day: int, day_dir: Path, hold_reason: str = "") -> str:
        if not self._available:
            print("[GitLab] Adapter not configured — skipping escalation issue.")
            return ""

        story_text = (day_dir / "story.md").read_text() if (day_dir / "story.md").exists() else "Not available"
        handoff_text = (day_dir / "handoff.md").read_text() if (day_dir / "handoff.md").exists() else "Not available"
        gate_text = (day_dir / "gate.md").read_text() if (day_dir / "gate.md").exists() else "Not available"
        if not hold_reason:
            gate_data = yaml.safe_load(gate_text) if (day_dir / "gate.md").exists() else {}
            hold_reason = (gate_data or {}).get("hold_reason", "")
        if not hold_reason and (day_dir / "sentinel.md").exists():
            hold_reason = (yaml.safe_load((day_dir / "sentinel.md").read_text()) or {}).get("hold_reason", "")
        if not hold_reason and (day_dir / "conduit.md").exists():
            hold_reason = (yaml.safe_load((day_dir / "conduit.md").read_text()) or {}).get("hold_reason", "")
        if not hold_reason:
            hold_reason = "Unknown — see agent reports below"

        body = f"""## Escalated HOLD — Day {day}

PACE could not resolve this HOLD after 2 retries. Human intervention required.

**Blocker:** {hold_reason}

---

### Story Card

```yaml
{story_text}
```

### FORGE Handoff (last attempt)

```yaml
{handoff_text}
```

### GATE Report (last attempt)

```yaml
{gate_text}
```

---

### To Resume

1. Resolve the blocker described above
2. Close this issue
3. Set the `PACE_PAUSED` CI/CD variable to `false`
4. The PACE loop will re-run Day {day} on the next scheduled trigger

> **Note:** `PACE_PAUSED` was automatically set to `true` when this issue was opened.

*Generated by PACE Orchestrator*"""

        try:
            resp = _requests.post(
                self._project_api("issues"),
                headers=self._headers(),
                json={
                    "title": f"[PACE HOLD] Day {day} — {hold_reason[:80]}",
                    "description": body,
                    "labels": f"pace-hold,pace-day-{day}",
                },
                timeout=15,
            )
            resp.raise_for_status()
            url = resp.json().get("web_url", "")
            print(f"[GitLab] Escalation issue opened: {url}")
            return url
        except Exception as e:
            print(f"[GitLab] Failed to open escalation issue: {e}")
            return ""

    # ------------------------------------------------------------------
    # Advisory findings
    # ------------------------------------------------------------------

    def push_advisory_items(self, day: int, items: list[dict], agent: str) -> str:
        if not self._available:
            print(f"[GitLab] Adapter not configured — skipping advisory issue for {agent}.")
            return ""
        if not items:
            return ""

        finding_lines = "\n".join(
            f"- [{item['id']}] {item['finding']}"
            for item in items
        )

        body = f"""## PACE Advisory — {agent} Day {day}

{agent} raised {len(items)} advisory finding(s) on Day {day} that were not resolved after one retry.

### Findings

{finding_lines}

---

### Resolution

1. Address each finding before the next clearance day
2. On a clearance day, SENTINEL/CONDUIT will verify and clear resolved items
3. Unresolved items on a clearance day become blockers (HOLD)

*Generated by PACE Orchestrator — Day {day}*"""

        try:
            resp = _requests.post(
                self._project_api("issues"),
                headers=self._headers(),
                json={
                    "title": f"[PACE Advisory] {agent} Day {day} — {len(items)} finding(s)",
                    "description": body,
                    "labels": f"pace-advisory,pace-{agent.lower()},pace-day-{day}",
                },
                timeout=15,
            )
            resp.raise_for_status()
            url = resp.json().get("web_url", "")
            print(f"[GitLab] Advisory issue opened: {url}")
            return url
        except Exception as e:
            print(f"[GitLab] Failed to open advisory issue: {e}")
            return ""

    # ------------------------------------------------------------------
    # Story ticket
    # ------------------------------------------------------------------

    def push_story(self, day: int, day_dir: Path) -> str:
        if not self._available:
            print("[GitLab] push_story: adapter not configured — skipping.")
            return ""
        story_file = day_dir / "story.md"
        if not story_file.exists():
            print(f"[GitLab] push_story: story.md not found in {day_dir}")
            return ""

        from issue_template import story_body_markdown
        story_card = yaml.safe_load(story_file.read_text()) or {}
        target = story_card.get("target", f"Day {day} story")
        try:
            resp = _requests.post(
                self._project_api("issues"),
                headers=self._headers(),
                json={
                    "title": f"[PACE Day {day}] {target}",
                    "description": story_body_markdown(day, story_card),
                    "labels": f"pace-story,pace-day-{day}",
                },
                timeout=15,
            )
            resp.raise_for_status()
            data = resp.json()
            url = data.get("web_url", "")
            iid = data.get("iid")
            self._save_ticket_ref(day_dir, {"url": url, "id": iid, "platform": "gitlab"})
            print(f"[GitLab] Story ticket opened: {url}")
            return url
        except Exception as e:
            print(f"[GitLab] push_story failed: {e}")
            return ""

    def update_story_status(self, day: int, day_dir: Path, status: str) -> None:
        if not self._available:
            return
        ref = self._load_ticket_ref(day_dir)
        iid = ref.get("id")
        if not iid:
            print(f"[GitLab] update_story_status: no ticket reference for Day {day}")
            return
        try:
            state_event = "close" if status == "done" else "reopen"
            _requests.put(
                self._project_api(f"issues/{iid}"),
                headers=self._headers(),
                json={"state_event": state_event},
                timeout=15,
            )
            print(f"[GitLab] Story issue !{iid} state_event → '{state_event}' (Day {day})")
        except Exception as e:
            print(f"[GitLab] update_story_status failed: {e}")

    def post_handoff_comment(self, day: int, day_dir: Path) -> None:
        if not self._available:
            return
        ref = self._load_ticket_ref(day_dir)
        iid = ref.get("id")
        handoff_file = day_dir / "handoff.md"
        if not iid or not handoff_file.exists():
            print(f"[GitLab] post_handoff_comment: missing ref or handoff.md for Day {day}")
            return
        from issue_template import handoff_comment_markdown
        handoff = yaml.safe_load(handoff_file.read_text()) or {}
        try:
            _requests.post(
                self._project_api(f"issues/{iid}/notes"),
                headers=self._headers(),
                json={"body": handoff_comment_markdown(day, handoff)},
                timeout=15,
            )
            print(f"[GitLab] Handoff comment posted to issue !{iid} (Day {day})")
        except Exception as e:
            print(f"[GitLab] post_handoff_comment failed: {e}")