"""PACE Jenkins Platform Adapter.

Uses the Jenkins REST API to poll build status for a given commit SHA.
Jenkins has no native PR/issue concept, so those operations write local files
(same as LocalAdapter) and print a notice.

Required environment variables:
    JENKINS_URL       — base URL of the Jenkins instance (e.g. http://jenkins:8080)
    JENKINS_USER      — username for HTTP Basic authentication
    JENKINS_TOKEN     — API token (from Jenkins → User → Configure → API Token)
    JENKINS_JOB_NAME  — full job path (e.g. "my-folder/my-pipeline" or "my-job")

How CI polling works:
    After FORGE pushes a commit, Jenkins picks it up via webhook or SCM polling.
    This adapter queries the job's recent builds and searches for one whose
    git revision (from the Git plugin) or changeSet matches the commit SHA.
    If no match is found within the timeout, it returns "timeout".

Limitations:
    - Requires the Jenkins Git plugin (standard in most installs).
    - Multi-branch pipelines are supported: set JENKINS_JOB_NAME to the branch
      path, e.g. "my-pipeline/main".
    - PR/issue operations are not natively supported; artifacts are written locally.
"""

from __future__ import annotations

import time
import yaml
from pathlib import Path

try:
    import requests
    _REQUESTS_AVAILABLE = True
except ImportError:
    _REQUESTS_AVAILABLE = False

from platforms.base import PlatformAdapter

_REPO_ROOT = Path(__file__).parent.parent.parent

# Number of recent builds to inspect when searching for a commit
_BUILD_SEARCH_DEPTH = 20


class JenkinsAdapter(PlatformAdapter):
    def __init__(self, url: str, user: str, token: str, job_name: str) -> None:
        self._url = url.rstrip("/") if url else ""
        self._auth = (user, token) if user and token else None
        self._job_name = job_name
        self._available = _REQUESTS_AVAILABLE and bool(self._url) and bool(self._job_name)
        if not _REQUESTS_AVAILABLE:
            print("[Jenkins] 'requests' not installed. Run: pip install requests")
        elif not self._url:
            print("[Jenkins] JENKINS_URL not set — CI polling disabled.")
        elif not self._job_name:
            print("[Jenkins] JENKINS_JOB_NAME not set — CI polling disabled.")

    # ------------------------------------------------------------------
    # Review PR — not natively supported; writes a local file
    # ------------------------------------------------------------------

    def open_review_pr(self, day: int, pace_dir: Path) -> str:
        print(
            f"[Jenkins] PR/MR not supported in Jenkins mode. "
            f"Writing review gate to local file instead."
        )
        # Delegate to file-based output (same logic as LocalAdapter)
        start_day = 1
        for candidate_start in [15, 29]:
            if day >= candidate_start:
                start_day = candidate_start
        period = f"Days {start_day}–{day}"

        ship_count, hold_count, deferred_items = 0, 0, []
        for d in range(start_day, day):
            gate_file = pace_dir / f"day-{d}" / "gate.md"
            if gate_file.exists():
                report = yaml.safe_load(gate_file.read_text())
                if report.get("gate_decision") == "SHIP":
                    ship_count += 1
                else:
                    hold_count += 1
                deferred_items.extend(report.get("deferred", []))

        total = ship_count + hold_count
        ship_rate = f"{(ship_count / total * 100):.0f}%" if total else "N/A"
        deferred_section = (
            "\n".join(f"- {item}" for item in deferred_items)
            if deferred_items
            else "None"
        )

        body = f"""# PACE Review Gate — {period} (Jenkins)

## Summary

| Metric | Value |
| --- | --- |
| Stories completed | {ship_count}/{total} |
| SHIP rate | {ship_rate} |
| Escalated HOLDs | {hold_count} |

## Deferred Acceptance Criteria

{deferred_section}

## To Continue

Review the artifacts in `.pace/day-{day}/`, then re-run the orchestrator
with `PACE_DAY={day + 1}` to proceed.

NOTE: Jenkins does not support automated PR creation. Consider integrating
with a Git hosting platform (GitHub/GitLab) for review gating.

---

*Generated by PACE Orchestrator — Day {day} (Jenkins mode)*"""

        out_file = pace_dir / f"day-{day}" / "review-pr.md"
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text(body)
        print(f"[Jenkins] Review gate written to: {out_file}")
        return str(out_file)

    # ------------------------------------------------------------------
    # Escalation issue — not natively supported; writes a local file
    # ------------------------------------------------------------------

    def open_escalation_issue(self, day: int, day_dir: Path) -> str:
        print(
            f"[Jenkins] Issue tracking not supported in Jenkins mode. "
            f"Writing escalation to local file."
        )
        story_text = (day_dir / "story.md").read_text() if (day_dir / "story.md").exists() else "Not available"
        handoff_text = (day_dir / "handoff.md").read_text() if (day_dir / "handoff.md").exists() else "Not available"
        gate_text = (day_dir / "gate.md").read_text() if (day_dir / "gate.md").exists() else "Not available"
        gate_data = yaml.safe_load(gate_text) if (day_dir / "gate.md").exists() else {}
        hold_reason = gate_data.get("hold_reason", "Unknown — see gate report")

        body = f"""# Escalated HOLD — Day {day} (Jenkins)

PACE could not resolve this HOLD after 2 retries. Human intervention required.

**Blocker:** {hold_reason}

---

## Story Card

```yaml
{story_text}
```

## FORGE Handoff (last attempt)

```yaml
{handoff_text}
```

## GATE Report (last attempt)

```yaml
{gate_text}
```

---

## To Resume

1. Resolve the blocker described above
2. Re-run: `PACE_DAY={day} python pace/orchestrator.py`

NOTE: Jenkins does not support automated issue creation. Consider integrating
with a Git hosting platform (GitHub/GitLab) for issue tracking.

*Generated by PACE Orchestrator (Jenkins mode)*"""

        out_file = day_dir / "escalation-issue.md"
        out_file.write_text(body)
        print(f"[Jenkins] Escalation written to: {out_file}")
        return str(out_file)

    # ------------------------------------------------------------------
    # CI polling — Jenkins REST API
    # ------------------------------------------------------------------

    def wait_for_commit_ci(
        self,
        sha: str,
        timeout_minutes: int = 15,
        poll_interval: int = 20,
    ) -> dict:
        if not self._available or not sha:
            print(f"[Jenkins] CI polling unavailable — returning no_runs.")
            return {"conclusion": "no_runs", "url": "", "name": "", "sha": sha or ""}

        deadline = time.time() + timeout_minutes * 60
        print(f"[Jenkins] Waiting for build of {sha[:8]} in job '{self._job_name}' (timeout: {timeout_minutes}m)...")

        # Encode slashes in multi-segment job paths (e.g. "folder/job" → "folder/job/job")
        job_path = "/".join(f"job/{segment}" for segment in self._job_name.split("/"))
        builds_url = f"{self._url}/{job_path}/api/json?tree=builds[number,result,url,actions[lastBuiltRevision[SHA1],remoteUrls],changeSet[items[commitId]]]{{0,{_BUILD_SEARCH_DEPTH}}}"

        while time.time() < deadline:
            try:
                resp = requests.get(builds_url, auth=self._auth, timeout=15)
                resp.raise_for_status()
                data = resp.json()
            except Exception as e:
                print(f"[Jenkins] API error: {e}")
                time.sleep(poll_interval)
                continue

            builds = data.get("builds", [])
            if not builds:
                print(f"[Jenkins] No builds found yet, waiting...")
                time.sleep(poll_interval)
                continue

            matched = _find_build_for_sha(builds, sha)
            if matched is None:
                print(f"[Jenkins] No build matching {sha[:8]} in last {_BUILD_SEARCH_DEPTH} builds, waiting...")
                time.sleep(poll_interval)
                continue

            result = matched.get("result")
            if result is None:
                # Build is in progress
                print(f"[Jenkins] Build #{matched.get('number')} in progress, waiting...")
                time.sleep(poll_interval)
                continue

            conclusion = _map_jenkins_result(result)
            build_url = matched.get("url", "")
            build_num = matched.get("number", "?")
            print(f"[Jenkins] Build #{build_num} complete — {result}")
            return {
                "conclusion": conclusion,
                "url": build_url,
                "name": f"build #{build_num}",
                "sha": sha,
            }

        print(f"[Jenkins] CI wait timed out after {timeout_minutes}m for {sha[:8]}")
        return {"conclusion": "timeout", "url": "", "name": "", "sha": sha}

    # ------------------------------------------------------------------
    # Summary / reporting
    # ------------------------------------------------------------------

    def post_daily_summary(self, day: int, gate_report: dict) -> None:
        decision = gate_report.get("gate_decision", "UNKNOWN")
        icon = "✅" if decision == "SHIP" else "🔴"
        print(f"[Jenkins] Day {day} summary: {icon} {decision}")

    def write_job_summary(self, markdown: str) -> None:
        # Write to workspace root as jenkins-summary.md
        # In a Jenkins pipeline, archive this file as a build artifact if needed.
        out_file = _REPO_ROOT / "jenkins-summary.md"
        out_file.write_text(markdown)
        print(f"[Jenkins] Job summary written to: {out_file}")


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _find_build_for_sha(builds: list[dict], sha: str) -> dict | None:
    """Search recent Jenkins builds for one whose git revision matches sha."""
    sha_lower = sha.lower()
    for build in builds:
        # Check via Git plugin lastBuiltRevision
        for action in build.get("actions", []):
            revision = action.get("lastBuiltRevision", {})
            if revision:
                rev_sha = revision.get("SHA1", "")
                if rev_sha and rev_sha.lower().startswith(sha_lower[:8]):
                    return build

        # Check via changeSet (works for freestyle + pipeline builds)
        for item in build.get("changeSet", {}).get("items", []):
            commit_id = item.get("commitId", "")
            if commit_id and commit_id.lower().startswith(sha_lower[:8]):
                return build

    return None


def _map_jenkins_result(result: str) -> str:
    """Map Jenkins build result to a PACE CI conclusion string."""
    mapping = {
        "SUCCESS": "success",
        "FAILURE": "failure",
        "UNSTABLE": "failure",
        "ABORTED": "cancelled",
        "NOT_BUILT": "no_runs",
    }
    return mapping.get(result.upper(), "failure")
