"""PACE Local Platform Adapters.

No-network adapters for running PACE locally without any CI/CD platform.

LocalCIAdapter:
- open_review_pr      → writes PR body to .pace/day-N/review-pr.md and prints the path
- wait_for_commit_ci  → returns immediately with conclusion="no_runs" (no CI to poll)
- post_daily_summary  → prints to stdout
- write_job_summary   → writes to pace-summary.md in the repo root

LocalTrackerAdapter:
- open_escalation_issue → writes issue body to .pace/day-N/escalation-issue.md
- push_advisory_items   → writes advisory body to .pace/advisory-dayN-agent.md

No environment variables required.
"""

from __future__ import annotations

import json
import yaml
from pathlib import Path

from platforms.base import CIAdapter, TrackerAdapter

# Repo root is two levels up from this file (pace/platforms/ → pace/ → repo root)
_REPO_ROOT = Path(__file__).parent.parent.parent


class LocalCIAdapter(CIAdapter):

    # ------------------------------------------------------------------
    # Review PR (written to a local file)
    # ------------------------------------------------------------------

    def open_review_pr(self, day: int, pace_dir: Path) -> str:
        start_day = 1
        for candidate_start in [15, 29]:
            if day >= candidate_start:
                start_day = candidate_start
        period = f"Days {start_day}–{day}"

        ship_count, hold_count, deferred_items = 0, 0, []
        for d in range(start_day, day):
            gate_file = pace_dir / f"day-{d}" / "gate.md"
            if gate_file.exists():
                report = yaml.safe_load(gate_file.read_text())
                if report.get("gate_decision") == "SHIP":
                    ship_count += 1
                else:
                    hold_count += 1
                deferred_items.extend(report.get("deferred", []))

        total = ship_count + hold_count
        ship_rate = f"{(ship_count / total * 100):.0f}%" if total else "N/A"
        deferred_section = (
            "\n".join(f"- {item}" for item in deferred_items)
            if deferred_items
            else "None"
        )

        body = f"""# PACE Review Gate — {period}

## Summary

| Metric | Value |
| --- | --- |
| Stories completed | {ship_count}/{total} |
| SHIP rate | {ship_rate} |
| Escalated HOLDs | {hold_count} |

## Deferred Acceptance Criteria

{deferred_section}

## To Continue

Review the artifacts in `.pace/day-{day}/`, then re-run the orchestrator
with `PACE_DAY={day + 1}` to proceed.

---

*Generated by PACE Orchestrator — Day {day} (local mode)*"""

        out_file = pace_dir / f"day-{day}" / "review-pr.md"
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text(body)
        print(f"[Local] Review gate written to: {out_file}")
        return str(out_file)

    # ------------------------------------------------------------------
    # CI polling — no-op (no CI in local mode)
    # ------------------------------------------------------------------

    def wait_for_commit_ci(
        self,
        sha: str,
        timeout_minutes: int = 15,
        poll_interval: int = 20,
    ) -> dict:
        print(f"[Local] CI polling skipped (local mode) for commit {sha[:8] if sha else 'unknown'}.")
        return {"conclusion": "no_runs", "url": "", "name": "", "sha": sha or ""}

    # ------------------------------------------------------------------
    # Summary / reporting
    # ------------------------------------------------------------------

    def post_daily_summary(self, day: int, gate_report: dict) -> None:
        decision = gate_report.get("gate_decision", "UNKNOWN")
        icon = "✅" if decision == "SHIP" else "🔴"
        print(f"[Local] Day {day} summary: {icon} {decision}")

    def write_job_summary(self, markdown: str) -> None:
        out_file = _REPO_ROOT / "pace-summary.md"
        out_file.write_text(markdown)
        print(f"[Local] Job summary written to: {out_file}")

    # ------------------------------------------------------------------
    # CI/CD variable management
    # ------------------------------------------------------------------

    def set_variable(self, name: str, value: str) -> bool:
        """Persist a named variable to .pace/variables.json for local mode."""
        variables_file = _REPO_ROOT / ".pace" / "variables.json"
        variables_file.parent.mkdir(parents=True, exist_ok=True)
        try:
            existing: dict = json.loads(variables_file.read_text()) if variables_file.exists() else {}
        except (json.JSONDecodeError, OSError):
            existing = {}
        existing[name] = value
        variables_file.write_text(json.dumps(existing, indent=2))
        print(f"[Local] Variable {name} set to {value!r} in {variables_file}")
        return True


class LocalTrackerAdapter(TrackerAdapter):

    # ------------------------------------------------------------------
    # Escalation issue (written to a local file)
    # ------------------------------------------------------------------

    def open_escalation_issue(self, day: int, day_dir: Path, hold_reason: str = "") -> str:
        story_text = (day_dir / "story.md").read_text() if (day_dir / "story.md").exists() else "Not available"
        handoff_text = (day_dir / "handoff.md").read_text() if (day_dir / "handoff.md").exists() else "Not available"
        gate_text = (day_dir / "gate.md").read_text() if (day_dir / "gate.md").exists() else "Not available"
        if not hold_reason:
            gate_data = yaml.safe_load(gate_text) if (day_dir / "gate.md").exists() else {}
            hold_reason = (gate_data or {}).get("hold_reason", "")
        if not hold_reason and (day_dir / "sentinel.md").exists():
            hold_reason = (yaml.safe_load((day_dir / "sentinel.md").read_text()) or {}).get("hold_reason", "")
        if not hold_reason and (day_dir / "conduit.md").exists():
            hold_reason = (yaml.safe_load((day_dir / "conduit.md").read_text()) or {}).get("hold_reason", "")
        if not hold_reason:
            hold_reason = "Unknown — see agent reports below"

        body = f"""# Escalated HOLD — Day {day}

PACE could not resolve this HOLD after 2 retries. Human intervention required.

**Blocker:** {hold_reason}

---

## Story Card

```yaml
{story_text}
```

## FORGE Handoff (last attempt)

```yaml
{handoff_text}
```

## GATE Report (last attempt)

```yaml
{gate_text}
```

---

## To Resume

1. Resolve the blocker described above
2. Delete or rename this file to acknowledge the escalation
3. Set `PACE_PAUSED=false` in your environment (or unset it)
4. Re-run: `PACE_DAY={day} python pace/orchestrator.py`

> **Note:** `PACE_PAUSED` was set to `true` in `.pace/variables.json` when this escalation was written.

*Generated by PACE Orchestrator (local mode)*"""

        out_file = day_dir / "escalation-issue.md"
        out_file.write_text(body)
        print(f"[Local] Escalation written to: {out_file}")
        return str(out_file)

    # ------------------------------------------------------------------
    # Advisory findings — written to local file
    # ------------------------------------------------------------------

    def push_advisory_items(self, day: int, items: list[dict], agent: str) -> str:
        if not items:
            return ""

        finding_lines = "\n".join(
            f"- [{item['id']}] {item['finding']}"
            for item in items
        )

        body = f"""# PACE Advisory — {agent} Day {day} (local mode)

{agent} raised {len(items)} advisory finding(s) on Day {day} that were not resolved after one retry.

## Findings

{finding_lines}

---

## Resolution

1. Address each finding before the next clearance day
2. On a clearance day, SENTINEL/CONDUIT will verify and clear resolved items
3. Unresolved items on a clearance day become blockers (HOLD)

*Generated by PACE Orchestrator (local mode) — Day {day}*"""

        out_file = _REPO_ROOT / ".pace" / f"advisory-day{day}-{agent.lower()}.md"
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text(body)
        print(f"[Local] Advisory written to: {out_file}")
        return str(out_file)